### ISSUE TITLE
add Windows instructions for installing GPG

### ISSUE THREAD

**Issue by whoburg** [whoburg/anonymous-feedback#17]

**Comment by whoburg** [comment]
here's a decent start, but it's a bit long and over the top: http://notes.jerzygangi.com/the-best-pgp-tutorial-for-mac-os-x-ever/

We also need a windows version.

For OSX, GPG Suite is a good option; main gotchas to highlight in instructions are:
 - deselecting GPGMail (On the "Installation Type" screen, under "Customize")
 - importance of not forgetting the key passphrase
 - setting keyboard shortcuts, if desired (we could also provide these instructions on the results page, where it's more relevant for users).

**Comment by whoburg** [comment]
Good start in #34. We still need instructions for Windows. Changing issue title accordingly.

**Comment by whoburg** [comment]
If someone wants to work on this, the instructions belong alongside the Mac instructions in `surveys/templates/surveys/signup.html`.

**Comment by matthewdominick** [comment]
Windows install and key gen instructions below. 

GPG for Windows instructions

1. Download GPG4Win (https://www.gpg4win.org). You can select $0 and download for free.
2. Install GPG4Win (check the boxes next to Kleopatra, GpgOL, and GpgEX).
3. Leave “Run Kleopatra” boxed at the end of the installer
4. Use Kleopatra to generate a new key pair.  Use your real name and an email address you can access.
5. Create a passphrase.  Do not forget it.  There is no way to recover it and you won’t be able to access your feedback. Fail.
6. Right click your new key in Kleopatra and select “Export.”  Save it on your computer and then open it with Notepad.  Once open in Notepad copy and paste the entire public key (including BEGIN and END flags) into the GPG Public Key textbox above.  

[[Put key_in_kleopatra.png image here.  It is in the Slack feedback_dev channel]]

**Comment by whoburg** [comment]
You rock. I'll get this into a PR now.

**Comment by whoburg** [comment]
This is superseded and fixed by #62
