### ISSUE TITLE
Sign Up Page Username

### ISSUE THREAD

**Issue by matthewdominick** [whoburg/anonymous-feedback#35]
We need to make it clear that the Username needs to be their first name.  Otherwise folks will have silly things like "feedbackmaster82."  Since we don't take actual name during signup we won't know who we are sending feedback to when "feedbackmaster82" appears in the drop down menu.

**Comment by whoburg** [comment]
Somewhat on top of this already. I'm extracting the user's full name from the public key, so the name that appears in the dropdown should be whatever full name the user entered during GPG public key creation.

**Comment by whoburg** [comment]
But point taken in terms of making sure people use a recognizable first and last name during key creation

**Comment by matthewdominick** [comment]
Copy.  I'll make new issue for GPG key creation instructions.

**Comment by whoburg** [comment]
That works. Alternatively, you can reopen this and change the title.
