### ISSUE TITLE
Clarify password entry for first-time decryption on "results" page

### ISSUE THREAD

**Issue by xyzena** [whoburg/anonymous-feedback#48]
Had to enter a password the first time I went to decrypt survey results 
- [x] (1) may be worth telling users that this will be required, and 
- [x] (2) it's also probably worth making it clear this is the GPG password they made in step 5 of "GPG Installation for Mac" rather than the password they created for their new ascan feedback account. (Or, if you think it's not a terrible idea, suggest that users make those two passwords the same?)

**Comment by whoburg** [comment]
Took a shot at this in #52
