### ISSUE TITLE
add GPG keyboard shortcut instructions for Windows

### ISSUE THREAD

**Issue by xyzena** [whoburg/anonymous-feedback#49]
Navigating to [the best pgp tutorial for mac ever](http://notes.jerzygangi.com/the-best-pgp-tutorial-for-mac-os-x-ever/) it was annoying to find "Step 3" since the page starts with a two-item list followed by a three-item list followed by a lot of text and images before you get to the actual Step 3. Low priority suggestion to just make your own instructions.

**Comment by whoburg** [comment]
agreed. This is halfway-fixed on #52. We still need to add instructions for setting keyboard shortcuts on Windows.

**Comment by whoburg** [comment]
changing issue title accordingly

**Comment by whoburg** [comment]
This is superseded by #61.
