### ISSUE TITLE
Results Page Instructions not compatible with Mailvelope

### ISSUE THREAD

**Issue by matthewdominick** [whoburg/anonymous-feedback#61]
Results page instructions are applicable only to GPG suite on Mac OS X.  See mailvelope decrypt instructions below. 

If you are using Mailvelope and this is the first time . . .
* Click on the Mailvelope icon in the upper right of your browser (looks like a lock and key)
* Select Advanced Options -> Activate on Current Tab +
* Select OK in the Authorized Domain popup window.  
* Return to ASCAN Feedback results.  You should be able to click the envelope in the middle of each encrypted block and decrypt locally with mailvelope.

**Comment by whoburg** [comment]
perfect, thanks. will get these added.
